apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clustral-agent.fullname" . }}-config
  labels:
    {{- include "clustral-agent.labels" . | nindent 4 }}
type: Opaque
data:
  cluster-id: {{ .Values.clusterId | b64enc | quote }}
  control-plane-url: {{ .Values.controlPlaneUrl | b64enc | quote }}
  {{- if .Values.bootstrapToken }}
  bootstrap-token: {{ .Values.bootstrapToken | b64enc | quote }}
  {{- end }}
