apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clustral-agent
  labels:
    app.kubernetes.io/name: clustral-agent
    app.kubernetes.io/component: agent
subjects:
  - kind: ServiceAccount
    name: clustral-agent
    namespace: clustral
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clustral-agent
