apiVersion: v1
kind: Namespace
metadata:
  name: clustral
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clustral-agent
  namespace: clustral
  labels:
    app.kubernetes.io/name: clustral-agent
    app.kubernetes.io/component: agent
automountServiceAccountToken: true
