apiVersion: v1
kind: Service
metadata:
  name: {{ include "clustral.fullname" . }}-api-gateway
  labels:
    {{- include "clustral.labels" . | nindent 4 }}
    {{- include "clustral.selectorLabels" (dict "root" . "component" "api-gateway") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    {{- include "clustral.selectorLabels" (dict "root" . "component" "api-gateway") | nindent 4 }}
