apiVersion: v1
kind: Service
metadata:
  name: {{ include "clustral.fullname" . }}-audit-service
  labels:
    {{- include "clustral.labels" . | nindent 4 }}
    {{- include "clustral.selectorLabels" (dict "root" . "component" "audit-service") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5200
      targetPort: http
      protocol: TCP
  selector:
    {{- include "clustral.selectorLabels" (dict "root" . "component" "audit-service") | nindent 4 }}
