apiVersion: v1
kind: Service
metadata:
  name: {{ include "clustral.fullname" . }}-controlplane-grpc
  labels:
    {{- include "clustral.labels" . | nindent 4 }}
    {{- include "clustral.selectorLabels" (dict "root" . "component" "controlplane") | nindent 4 }}
  {{- with .Values.controlplane.grpcService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controlplane.grpcService.type }}
  ports:
    - name: grpc
      port: {{ .Values.controlplane.grpcService.port }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "clustral.selectorLabels" (dict "root" . "component" "controlplane") | nindent 4 }}
