{{- if and .Values.gatewayApi.enabled .Values.gatewayApi.grpcRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ include "clustral.fullname" . }}-grpc
  labels:
    {{- include "clustral.labels" . | nindent 4 }}
  {{- with .Values.gatewayApi.grpcRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ .Values.gatewayApi.gatewayRef.name }}
      {{- if .Values.gatewayApi.gatewayRef.namespace }}
      namespace: {{ .Values.gatewayApi.gatewayRef.namespace }}
      {{- end }}
      port: {{ .Values.controlplane.grpcService.port }}
  rules:
    - backendRefs:
        - name: {{ include "clustral.fullname" . }}-controlplane-grpc
          port: {{ .Values.controlplane.grpcService.port }}
{{- end }}
