{{- if .Values.podDisruptionBudget.enabled }}
{{- $fullname := include "clustral.fullname" . -}}
{{- $components := list "controlplane" "api-gateway" "audit-service" "web" -}}
{{- range $component := $components }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $fullname }}-{{ $component }}
  labels:
    {{- include "clustral.labels" $ | nindent 4 }}
    {{- include "clustral.selectorLabels" (dict "root" $ "component" $component) | nindent 4 }}
spec:
  maxUnavailable: {{ $.Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "clustral.selectorLabels" (dict "root" $ "component" $component) | nindent 6 }}
{{- end }}
{{- end }}
