{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "clustral.fullname" . }}-audit-service
  labels:
    {{- include "clustral.labels" . | nindent 4 }}
    {{- include "clustral.selectorLabels" (dict "root" . "component" "audit-service") | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "clustral.selectorLabels" (dict "root" . "component" "audit-service") | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
